### ISSUE TITLE
"Bus error: an error counter reached the 'heavy'/'warning' limit" with Elobau Canopen angle sensor

### ISSUE THREAD

**Issue by Topper69** [christiansandberg/canopen#305]
Hi,

I'm trying to read & configure Elobau canopen angle sensor with a Peak PCAN-USB FD reader.
Wiring :
DEUTSCH Sensor connector  ---  PEAK
PIN 1 GND
PIN 2 +12V power supply
PIN 5 (can L)                        --- CAN L
PIN 6 (can H)                       --- CAN H
120Ohm between pin 5&6.

OS : Windows 10 64b + python3.10.2
Example python sketch:

import canopen
network = canopen.Network()
network.connect(bustype='pcan', channel='PCAN_USBBUS1', bitrate=250000) 
##green light is flashing
network.scanner.search()
##error : Bus error: an error counter reached the 'heavy'/'warning' limit
##Peak is flashing red

Any clue what's going on?

Many thanks.

**Comment by af-silva** [comment]
Hi @Topper69,

>PCAN_ERROR_BUSHEAVY: Indicates a bus error within the given PCAN Channel. The hardware is in bus-heavy status

It can a number of things related to Network:
- Is the bus correctly terminate? (I will assume yes since you mentions the resistor);
- Are you using the correct bitrate for the given adapter?;
- How many devices do you now on the bus, one? or more? if more they are all configured equal, this is with the same bitrate?
- Do you have the drives updated or using the correct/recomended version?
- Have you tried, using candump and cansend to try communicate with the device beforehand and check if the connection is ok?

Please check the forums and documentation from [Peak](forum.peak-system.com) -> [BUSLIGHT, BUSHEAVY & BUSOFF](https://forum.peak-system.com/viewtopic.php?f=120&t=39)

In the past I have used SockectCan to connect but I was on linux.

Have you tried this -> `network.connect(bustype='pcan', channel='PCAN_USBBUS1', state=BusState.ACTIVE, bitrate=500000)` ( from the python-can documentation [here](https://python-can.readthedocs.io/en/master/interfaces/pcan.html) )

Good luck ;)

**Comment by Topper69** [comment]
Bad wiring ;) working good now (i have mirrored the wiring).
Closed the issue.
Many thanks for the help.
