### ISSUE TITLE
Incompatibilities with version 2.0.0 of canopen.py

### ISSUE THREAD

**Issue by j-corvo** [christiansandberg/canopen#314]
Hello,

I recently stumbled into an issue. I was using the version 1.2.1 of this library on my computer and it runnned perfectly. Then I run my code into a new one. On the new computer, I wasn't able to transition from the node state of 'NOT READY TO SWITCH ON' to 'OPERATIONAL', whereas in my computer it worked fine.
I wondered what would be wrong because the drivers, the library and the code were the same, so I took a look at the library versions that I've installed in each computer and turned out that the version on the new computer were the 2.0.0 and on my computer were 1.2.1. When I changed the version on the new computer it worked.
I am just raising this question because it can be any incompatibility issue that wasn't resolved properly and other people could be having the same problem.

System: Linux 20.04 LTS

Thanks for the attention

**Comment by af-silva** [comment]
Hi, @j-corvo,

We are aware and the changes are mention on the release notes like acolomb mention. To use the newer version you have to make some changes to your code, since from version 2.0.0 the code is more streamline and there are less assumptions on how some parts of the DS402 were handled, and it should now be implemented in the "user" code. 

Thanks. Closing this since it's not a problem.
