### ISSUE TITLE
CANOpen Log file

### ISSUE THREAD

**Issue by smita6789** [christiansandberg/canopen#387]
Hello,

We tried using many options like log, logger, MessageListener etc. 
Is there any way to capture the log for the SDO and PDO in text file or any other format?

Details similar to PCAN-View trace file, like timestamp, CAN ID, request, response and so on

**Comment by acolomb** [comment]
Depends on your operating system. On Linux and similar, there is the simple `candump` command.  Or you can use `libpcap` based tools such as Wireshark because well-behaved CAN interfaces implement the SocketCAN standard, which looks like a network adapter.

On Windows, PCAN-View is an option and I've heard of people getting Wireshark to work there as well.  But it depends very much on your adapter, as there is no real standard interface on Windows.

On MacOS I don't know.

**Comment by smita6789** [comment]
Hello,

Thanks for your reply.

I am using PCAN-View to capture CANOpen trace manually.
I am looking for the way to do the same through python.
Is there any way to capture log through python script and store in a file?

We are looking for automated way, may be with help of canopen or any other library.

Thanks,
Smita



Classified as Business

**Comment by acolomb** [comment]
Closing after no feedback following the latest recommendation.
