### ISSUE TITLE
`import_od` and `export_od` are undocumented

### ISSUE THREAD

**Issue by erlend-aasland** [christiansandberg/canopen#472]
_Disclaimer: apologies in advance if these are intentionally excluded from the docs._

It seems to me, judging from their docstrings, that `import_od` and `export_od` have been unintentionally excluded from the docs. Adding them is trivial:

```diff
diff --git a/doc/od.rst b/doc/od.rst
index 6040bb5..4b88e5f 100644
--- a/doc/od.rst
+++ b/doc/od.rst
@@ -54,6 +54,10 @@ You can access the objects using either index/subindex or names::
 API
 ---
 
+.. autofunction:: canopen.export_od
+
+.. autofunction:: canopen.import_od
+
 .. autoclass:: canopen.ObjectDictionary
    :members:
```

However, I think this simple patch should be coupled with some minor improvements of the docstrings in question. I can open a PR, unless you prefer these APIs should remain undocumented.

**Comment by acolomb** [comment]
I don't have a strong opinion here, but for import_od, it's usually not needed because the ObjectDictionary is instantiated when creating a node class. Passing a pre-created instance during node construction is possible, but usually in conjunction with a programmatically created ObjectDictionary, not by reading an EDS.

But it's a public API with valid use cases, so sure why not expose the documentation. Happy to review a PR with docstring fixes as well.
